services:
  database:
    image: postgres:16
    container_name: ${APP_NAME}-db
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      PGPASSWORD: ${DB_PASSWORD:-secret}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - ./docker/volumes/pgsql:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-q'
        - '-d'
        - '${DB_DATABASE}'
        - '-U'
        - '${DB_USERNAME}'
      retries: 3
      timeout: 5s


  php:
    container_name: ${APP_NAME}-php
    build:
      context: ./docker/containers/php
    ports:
      - '9000'
    volumes:
      - ./:/var/www/html/
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./docker/containers/php/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - redis
      - database


  redis:
    container_name: ${APP_NAME}-redis
    image: redis:alpine
    command: redis-server        
    volumes:
      - ./docker/volumes/redis:/data'
    ports:
      - "6379"

  nginx:
    container_name: ${APP_NAME}-nginx
    image: nginx:stable-alpine
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./:/var/www/html/
      - ./docker/containers/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - database
      - php