name: tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Set up Docker Compose
        run: docker-compose up -d --build

      - name: Install Dependencies
        run: |
          docker-compose exec -T composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Install Node Dependencies
        run: docker-compose exec -T npm ci

      - name: Generate Application Key
        run: docker-compose exec -T php artisan key:generate

      - name: Publish Ziggy Configuration
        run: docker-compose exec -T php artisan ziggy:generate

      - name: Build Assets
        run: docker-compose exec -T npm run build

      - name: Tests
        run: docker-compose exec -T ./vendor/bin/phpunit
